const dummyData = {
  categories: [
    { name: 'Burgers', description: 'Signature gourmet burgers' },
    { name: 'Pizzas', description: 'Stone baked artisan pizzas' },
    { name: 'Burritos', description: 'Fusion wraps with bold flavors' },
    { name: 'Sandwiches', description: 'Cafe style stacked sandwiches' },
    { name: 'Wraps', description: 'Grilled wraps with house sauces' },
    { name: 'Bowls', description: 'Wholesome rice & protein bowls' },
  ],

  customizations: [
    { name: 'Extra Cheese', price: 40, type: 'topping' },
    { name: 'Jalapeños', price: 25, type: 'topping' },
    { name: 'Onions', price: 20, type: 'topping' },
    { name: 'Olives', price: 30, type: 'topping' },
    { name: 'Mushrooms', price: 30, type: 'topping' },
    { name: 'Tomatoes', price: 15, type: 'topping' },
    { name: 'Beef Bacon', price: 80, type: 'topping' },
    { name: 'Avocado', price: 70, type: 'topping' },

    { name: 'Coke', price: 40, type: 'side' },
    { name: 'Fries', price: 90, type: 'side' },
    { name: 'Garlic Bread', price: 120, type: 'side' },
    { name: 'Chicken Nuggets', price: 150, type: 'side' },
    { name: 'Iced Tea', price: 60, type: 'side' },
    { name: 'Salad', price: 100, type: 'side' },
    { name: 'Potato Wedges', price: 110, type: 'side' },
    { name: 'Mozzarella Sticks', price: 180, type: 'side' },
    { name: 'Sweet Corn', price: 70, type: 'side' },
    { name: 'Choco Lava Cake', price: 180, type: 'side' },
  ],

  menu: [
    {
      name: 'Dhanmondi Classic Beef Burger',
      description: 'Juicy grilled beef patty, cheddar, lettuce & house sauce',
      image_url:
        'https://static.vecteezy.com/system/resources/previews/044/844/600/large_2x/homemade-fresh-tasty-burger-with-meat-and-cheese-classic-cheese-burger-and-vegetable-ai-generated-free-png.png',
      price: 349,
      rating: 4.7,
      calories: 600,
      protein: 30,
      category_name: 'Burgers',
      customizations: ['Extra Cheese', 'Coke', 'Fries', 'Onions', 'Beef Bacon'],
    },
    {
      name: 'Smoked Pepperoni Delight',
      description: 'Loaded with premium pepperoni & mozzarella',
      image_url:
        'https://static.vecteezy.com/system/resources/previews/023/742/417/large_2x/pepperoni-pizza-isolated-illustration-ai-generative-free-png.png',
      price: 799,
      rating: 4.8,
      calories: 850,
      protein: 35,
      category_name: 'Pizzas',
      customizations: [
        'Extra Cheese',
        'Jalapeños',
        'Garlic Bread',
        'Coke',
        'Olives',
      ],
    },
    {
      name: 'Cafe Style Chicken Burrito',
      description: 'Grilled chicken, rice & creamy salsa wrapped fresh',
      image_url:
        'https://static.vecteezy.com/system/resources/previews/055/133/581/large_2x/deliciously-grilled-burritos-filled-with-beans-corn-and-fresh-vegetables-served-with-lime-wedge-and-cilantro-isolated-on-transparent-background-free-png.png',
      price: 299,
      rating: 4.4,
      calories: 520,
      protein: 26,
      category_name: 'Burritos',
      customizations: ['Jalapeños', 'Iced Tea', 'Fries', 'Salad'],
    },
    {
      name: 'BBQ Bacon Gourmet Burger',
      description: 'Smoky BBQ glaze, crispy beef bacon & cheddar',
      image_url:
        'https://static.vecteezy.com/system/resources/previews/060/236/245/large_2x/a-large-hamburger-with-cheese-onions-and-lettuce-free-png.png',
      price: 379,
      rating: 4.9,
      calories: 720,
      protein: 34,
      category_name: 'Burgers',
      customizations: ['Onions', 'Fries', 'Coke', 'Beef Bacon', 'Avocado'],
    },
    {
      name: 'Grilled Chicken Caesar Wrap',
      description: 'Tender grilled chicken with creamy Caesar dressing',
      image_url:
        'https://static.vecteezy.com/system/resources/previews/048/930/603/large_2x/caesar-wrap-grilled-chicken-isolated-on-transparent-background-free-png.png',
      price: 289,
      rating: 4.5,
      calories: 500,
      protein: 28,
      category_name: 'Wraps',
      customizations: ['Extra Cheese', 'Coke', 'Potato Wedges', 'Tomatoes'],
    },
    {
      name: 'Mediterranean Veggie Sandwich',
      description: 'Roasted vegetables, pesto & melted cheese',
      image_url:
        'https://static.vecteezy.com/system/resources/previews/047/832/012/large_2x/grilled-sesame-seed-bread-veggie-sandwich-with-tomato-and-onion-free-png.png',
      price: 259,
      rating: 4.3,
      calories: 430,
      protein: 20,
      category_name: 'Sandwiches',
      customizations: ['Mushrooms', 'Olives', 'Mozzarella Sticks', 'Iced Tea'],
    },
    {
      name: 'Double Smash Beef Burger',
      description: 'Two smashed patties, double cheese & signature sauce',
      image_url:
        'https://static.vecteezy.com/system/resources/previews/060/359/627/large_2x/double-cheeseburger-with-lettuce-tomatoes-cheese-and-sesame-bun-free-png.png',
      price: 449,
      rating: 4.9,
      calories: 820,
      protein: 38,
      category_name: 'Burgers',
      customizations: [
        'Extra Cheese',
        'Onions',
        'Fries',
        'Coke',
        'Chicken Nuggets',
      ],
    },
    {
      name: 'Paneer Tikka Fusion Wrap',
      description: 'Spiced paneer, mint sauce & fresh veggies',
      image_url:
        'https://static.vecteezy.com/system/resources/previews/057/913/530/large_2x/delicious-wraps-a-tantalizing-array-of-wraps-filled-with-vibrant-vegetables-succulent-fillings-and-fresh-ingredients-artfully-arranged-for-a-mouthwatering-culinary-experience-free-png.png',
      price: 279,
      rating: 4.6,
      calories: 480,
      protein: 22,
      category_name: 'Wraps',
      customizations: ['Jalapeños', 'Tomatoes', 'Salad', 'Fries', 'Iced Tea'],
    },
    {
      name: 'Mexican Fiesta Rice Bowl',
      description: 'Rice, grilled chicken, corn & guacamole',
      image_url:
        'https://static.vecteezy.com/system/resources/previews/057/466/374/large_2x/healthy-quinoa-bowl-with-avocado-tomato-and-black-beans-ingredients-free-png.png',
      price: 339,
      rating: 4.7,
      calories: 650,
      protein: 30,
      category_name: 'Bowls',
      customizations: ['Avocado', 'Sweet Corn', 'Salad', 'Iced Tea'],
    },
    {
      name: 'Spicy Crispy Chicken Sandwich',
      description: 'Golden fried chicken with spicy mayo & pickles',
      image_url:
        'https://static.vecteezy.com/system/resources/previews/051/814/008/large_2x/a-grilled-chicken-sandwich-with-lettuce-and-tomatoes-free-png.png',
      price: 299,
      rating: 4.4,
      calories: 560,
      protein: 27,
      category_name: 'Sandwiches',
      customizations: [
        'Jalapeños',
        'Onions',
        'Fries',
        'Coke',
        'Choco Lava Cake',
      ],
    },
    {
      name: 'Classic Margherita Supreme',
      description: 'Fresh tomato sauce, mozzarella & basil',
      image_url:
        'https://static.vecteezy.com/system/resources/previews/058/700/845/large_2x/free-isolated-on-transparent-background-delicious-pizza-topped-with-fresh-tomatoes-basil-and-melted-cheese-perfect-for-food-free-png.png',
      price: 699,
      rating: 4.3,
      calories: 620,
      protein: 24,
      category_name: 'Pizzas',
      customizations: ['Extra Cheese', 'Olives', 'Coke', 'Garlic Bread'],
    },
    {
      name: 'Protein Boost Chicken Bowl',
      description: 'Grilled chicken, quinoa & fresh greens',
      image_url:
        'https://static.vecteezy.com/system/resources/previews/056/106/379/large_2x/top-view-salad-with-chicken-avocado-tomatoes-and-lettuce-free-png.png',
      price: 359,
      rating: 4.8,
      calories: 600,
      protein: 40,
      category_name: 'Bowls',
      customizations: ['Avocado', 'Salad', 'Sweet Corn', 'Iced Tea'],
    },
    {
      name: 'Paneer Fiesta Burrito',
      description: 'Paneer cubes, rice & spicy fusion sauce',
      image_url:
        'https://static.vecteezy.com/system/resources/previews/056/565/254/large_2x/burrito-with-cauliflower-and-vegetables-free-png.png',
      price: 299,
      rating: 4.3,
      calories: 520,
      protein: 23,
      category_name: 'Burritos',
      customizations: ['Jalapeños', 'Fries', 'Garlic Bread', 'Coke'],
    },
    {
      name: 'Cafe Style Chicken Club',
      description: 'Triple layered grilled chicken & cheese sandwich',
      image_url:
        'https://static.vecteezy.com/system/resources/previews/060/364/135/large_2x/a-flavorful-club-sandwich-with-turkey-bacon-and-fresh-vegetables-sliced-and-isolated-on-a-transparent-background-free-png.png',
      price: 329,
      rating: 4.6,
      calories: 640,
      protein: 32,
      category_name: 'Sandwiches',
      customizations: ['Beef Bacon', 'Tomatoes', 'Mozzarella Sticks', 'Iced Tea'],
    },
  ],
}

export default dummyData